FROM ubuntu:24.04

# Install dependencies.
# RUN apt-get update && apt-get install -y wget steghide && rm -rf /var/lib/apt/lists/*
RUN apt-get update && apt-get install -y wget python3.12 pipx steghide && rm -rf /var/lib/apt/lists/*

# Install pipx and poetry
RUN pipx ensurepath && \
    pipx install poetry

# WORKDIR is /engine so storing overflowengine can be triggered by ./overflowengine 
# Running it from a file in app_cough does not matter as engine is current working directory
WORKDIR /engine

# Install poetry dependencies (just need boto3 + celery, but just lazy in this case)
COPY pyproject.toml ./

# Temp pipx managed poetry instance that installs all dependencies into a persistent virtual env (/app/.venv/) due to above command
RUN pipx run poetry install --no-root

# Copy app that contains engine across
COPY app_cough app_cough

# Updated computer architecture selection of the OverflowEngine binary.
# This appears to work on Windows, Macs, and EC2 AMD64 and ARM64 instances.
RUN ARCH=$(dpkg --print-architecture) && \
    if [ "$ARCH" = "amd64" ]; then \
        wget https://github.com/CSSE6400/CoughOverflow-Engine/releases/download/v1.0/overflowengine-amd64 -O overflowengine; \
    else \
        wget https://github.com/CSSE6400/CoughOverflow-Engine/releases/download/v1.0/overflowengine-arm64 -O overflowengine; \
    fi && \
    chmod +x overflowengine

COPY worker.sh /engine/worker.sh
RUN chmod +x /engine/worker.sh
ENTRYPOINT [ "/engine/worker.sh" ]
# CMD ["pipx", "run", "poetry", "run", "celery", "--app", "app_cough.tasks.analysis:celery", "worker", "--loglevel=info"]
